language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- yarn build
install:
  npm install -g firebase-tools
deploy:
  provider: firebase
  project: "happy-habit"
  token:
    secure: yQtmDGRtrcTYL1QPY2I0HAPXUrxQkL8gytYBLUv+HqxvXf2XRSw/vNLxThWwheteFszz5Muf75JyElxaVlAWHW/V2H1xSWxM+kOTKm5yU9GbRgp7OcYwa0KdaSF5aHq46kjRnMiX1kq5a+d40OYqvZr7zgYZK5SFMYgZytFED+bhcd7xX0AoPUFfh40vWJgos06RHPZ2zCah4Dl3ppHuFO4LOpVqfm7q3BdH0yJltLxQ7RFLz1JMhWWh+qg+e4WtRivZDfmLDi+J7zFgTpn71SWRn/GFkLFxWb4TFzlyn1NhVT23KBxVXTMCE2xmRlCFMf5rTOtRNcK/tp5aFAdtBjrhab1rB8K3MHl314I71tNDGl5Lq6pu9Lvo/LEVfpNb/BRzKlfx12ucCWIa9LJETcgmolHjqeGqGQ33RXzilbvf7F2GqzS9qPQ3KNR/f6H5NPCtOE7qPy/Na3JONtNc5LZlIf3TexGX3FQCaElQxErRpQ6e6Kg4OgD7u7q9RPxZiDSRQfRxQ9c0fYIblVqK9ZJxhXZTcUxMjB5sDtjzvxsWta0JvJrpPEpiIZd/3bkxc/Llf89jpZ6PtPNcowVuT8jGVEjiQ9APWwS3HpWQu3bAikw/fKMwPRNSq2EnIuUYjB3Huzdy7rNbuBaj9QTOpXKjQC+AOvjMsuw0K0cevB0=
  local_dir: build
  skip_cleanup: true
  on:
    branch: master